
version: "3.9"

services:
  # Kafka Broker & Controller Node 1
  kafka1:
    image: apache/kafka:3.7.0                # Officiell Kafka-image (KRaft-mode, utan ZooKeeper)
    hostname: kafka1                         # Internt hostname för Kafka
    container_name: kafka1                   # Namn på container för enklare hantering
    restart: unless-stopped                  # Startar om automatiskt vid krasch eller Docker-omstart
    ports:
      - "9092:9092"                          # Port för klientanslutning till Kafka1
    environment:
      KAFKA_NODE_ID: 1                       # Unik identifierare i klustret
      KAFKA_PROCESS_ROLES: broker,controller # Roller för Kafka-noden (både broker och controller)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093 # Kafka controller quorum
      KAFKA_LISTENERS: >
        PLAINTEXT://kafka1:9092,
        CONTROLLER://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092 # Hur Kafka annonserar sig internt i nätverket
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER # Namnet på den interna controller-lyssnaren
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT # Listener för kommunikation mellan brokers
      KAFKA_LOG_RETENTION_HOURS: 72          # Sparar loggar i 72 timmar innan rensning
      KAFKA_LOG_DIRS: /var/lib/kafka/data    # Mapp för persistent Kafka-data
    volumes:
      - kafka1-data:/var/lib/kafka/data      # Persistent Kafka-data (volym)
    networks:
      - kafka-net                            # Docker-nätverk för inter-container-kommunikation

  # Kafka Broker & Controller Node 2
  kafka2:
    image: apache/kafka:3.7.0
    hostname: kafka2
    container_name: kafka2
    restart: unless-stopped
    ports:
      - "9094:9094"                          # Port för klientanslutning till Kafka2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LISTENERS: >
        PLAINTEXT://kafka2:9094,
        CONTROLLER://kafka2:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_RETENTION_HOURS: 72
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka2-data:/var/lib/kafka/data
    networks:
      - kafka-net

  # Kafka Broker & Controller Node 3
  kafka3:
    image: apache/kafka:3.7.0
    hostname: kafka3
    container_name: kafka3
    restart: unless-stopped
    ports:
      - "9096:9096"                          # Port för klientanslutning till Kafka3
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LISTENERS: >
        PLAINTEXT://kafka3:9096,
        CONTROLLER://kafka3:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9096
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_RETENTION_HOURS: 72
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka3-data:/var/lib/kafka/data
    networks:
      - kafka-net

  # Kafdrop – Webbaserat Kafka UI
  kafdrop:
    image: obsidiandynamics/kafdrop          #  Kafka UI-container
    container_name: kafdrop
    restart: unless-stopped
    ports:
      - "9000:9000"                          # UI på http://localhost:9000
    environment:
      KAFKA_BROKER_CONNECT: kafka1:9092,kafka2:9094,kafka3:9096 # Ansluter till alla Kafka-noder
      JVM_OPTS: "-Xms32M -Xmx256M"           # JVM-inställningar (minnesoptimerat)
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka-net

# Persistenta volymer för Kafka-data så att data behålls vid omstart
volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data:

# Docker-nätverk för kommunikation för alla containrar
networks:
  kafka-net:
